mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from recipesapp.views import RecipeIndexView

urlpatterns = [
    path("", RecipeIndexView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('recipe/', include('recipesapp.urls')),
    path('user/', include('userslist.urls')),
    path('api/', include('myapiapp.urls')),
]

urlpatterns += i18n_patterns(
    path('user/', include('userslist.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

mysite/recipesapp/urls.py
from django.urls import path

from .views import RecipeIndexView,\
    RecipeListView, \
    RecipeDetailsView,\
    RecipeCreateView,\
    RecipeUpdateView,\
    RecipeDeleteView


app_name = 'recipesapp'

urlpatterns = [
    path('', RecipeIndexView.as_view(), name='index'),
    path('list/', RecipeListView.as_view(), name='list'),
    path('recipe/create/', RecipeCreateView.as_view(), name='recipe_create'),
    path('list/<int:pk>/', RecipeDetailsView.as_view(), name='recipe_details'),
    path('list/<int:pk>/update', RecipeUpdateView.as_view(), name='recipe_update'),
    path('list/<int:pk>/delete', RecipeDeleteView.as_view(), name='recipe_delete'),
]

mysite/userslist/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import get_cookie_view, \
    set_cookie_view, get_session_view, \
    set_session_view, logout_view,\
    AboutMeView, RegisterView,\
    HelloView, user_update

app_name = 'userslist'

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name="userslist/login.html",
                            redirect_authenticated_user=True),
         name='login'),
    path('hello/', HelloView.as_view(), name='hello'),
    path('logout/', logout_view, name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('edit-user/', user_update, name='edit-user'),
    path('cookie/get', get_cookie_view, name='get-cookie'),
    path('cookie/set', set_cookie_view, name='set-cookie'),
    path('session/get', get_session_view, name='get-session'),
    path('session/set', set_session_view, name='set-session'),
]

mysite/userslist/models.py
from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/',
                              blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'

mysite/userslist/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Profile

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
    def clean_email(self):
        data = self.cleaned_data['email']
        qs = User.objects.exclude(id=self.instance.id)\
                         .filter(email=data)
        if qs.exists():
            raise forms.ValidationError('Указанный адрес эл.почты уже существует в системе!')
        return data


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['date_of_birth', 'photo']

mysite/userslist/views.py
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpRequest, HttpResponse, request
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, UpdateView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from .forms import UserForm, ProfileForm, User
from .models import Profile

class HelloView(View):
    welcome_message = _('Welcome everyone!!!')
    def get(self, request: HttpRequest):
        return HttpResponse(f"<h1>{self.welcome_message}</h1>")

class AboutMeView(TemplateView):
    template_name = 'userslist/about-me.html'
class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'userslist/register.html'
    success_url = reverse_lazy('recipesapp:list')
    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(self.request,
            username=username, password=password)
        login(request=self.request, user=user)
        return response

def login_view(request: HttpRequest):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('recipesapp:list')
        else:
            return render(request, 'userslist/login.html')

    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('recipesapp:list')
        # return HttpResponse('Authenticated successfully')
    else:
        return render(request, 'userslist/login.html', {'error': 'Invalid username or password'})


def logout_view(request: HttpRequest):
    logout(request)
    # return redirect('userslist:login')
    return redirect('recipesapp:list')






@login_required
def user_update(request):
    if request.method == 'POST':
        user_form = UserForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileForm(
                                    instance=request.user.profile,
                                    data=request.POST,
                                    files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Данные пользователя изменены.')
        else:
            messages.error(request, "ВНЕСЕНЫ НЕКОРРЕКТНЫЕ ДАННЫЕ!")
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request,
                  'userslist/user_update_form.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})


def set_cookie_view(request: HttpRequest):
    response = HttpResponse("Cookie set")
    response.set_cookie('fizz', 'buzz', max_age=3600)
    return response

def get_cookie_view(request: HttpRequest):
    fizz_value = request.COOKIES.get("fizz", "default value")
    return HttpResponse(f"Cookie value: {fizz_value!r}")
@permission_required("userslist:view_profile", raise_exception=True)
def set_session_view(request: HttpRequest):
    request.session['fizz'] = 'buzz'
    return HttpResponse("Session set")


def get_session_view(request: HttpRequest):
    value = request.session.get('fizz', 'default value')
    return HttpResponse(f"Session value: {value!r}")

mysite/userslist/templates/userslist/about-me.html
<!DOCTYPE html>

{% extends 'userslist/base.html' %}
{% load static %}

<html>
<head>
 <meta charset="utf-8" />
  {% block title %}
    <title>Сайт простых рецептов.Профиль пользователя</title>
  {% endblock %}
</head>
<body>

  {% block content %}
  <h3 style="display: flex; justify-content: center; color: #DD3333">Личный кабинет пользователя </h3>
  <div class="card text-center">
    <div class="card-body">
    {% if user.is_authenticated %}
        <h5 class="card-title">
          <p>Имя пользователя: {{ user.username }}</p>
          <p>Имя: {{ user.first_name }}</p>
          <p>Фамилия: {{ user.last_name }}</p>
          <p>Email: {{ user.email }}</p>
          <p>Дата рождения: {{user.profile.date_of_birth}}</p>
          {% if user.profile.photo %}
            <img class="card-img-top" style="width:50%" src="{{ user.profile.photo.url }}" alt="">
          {% else %}
            <p style="color: red">Фото отсутствует.</p>
          {% endif %}
    {% else %}
          <p>Вы не авторизованы. Пожалуйста, авторизуйтесь.</p>
    {% endif %}
        </h5>
    </div>
  </div>
  <div class="form-group py-3">
    <a class="btn btn-outline-info"
       href="{% url 'userslist:edit-user' %}">Изменить профиль</a>
  </div>
    <div class="form-group py-3">
      <a class="btn btn-outline-primary"
         href="{% url 'recipesapp:list' %}">Вернуться к списку рецептов</a>
    </div>
  {% endblock %}
</body>
</html>

mysite/userslist/templates/userslist/base.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
  {% block title %}
  <title></title>
  {% endblock %}
  <link href="{% static 'css/base.css' %}" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
    crossorigin="anonymous"
  />
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="nav-link active" style="color: aliceblue;" href="{% url 'recipesapp:index' %}">Главная</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="nav-link active" style="color: aliceblue;" href="{% url 'recipesapp:list' %}">Рецепты</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>


        <div class="d-flex justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" style="color: aliceblue;" href="{% url 'recipesapp:recipe_create' %}">
                  Добавить рецепт</a>
              </li>
                <a href="{% url 'userslist:about-me' %}" class="nav-link active" style="color: aliceblue;">Мой профиль</a>
                <a  class="nav-link active" style="color: aliceblue;" href="{% url 'userslist:logout' %}">Выйти</a>

              {% else %}
                <a class="nav-link active" style="color: aliceblue;" href="{% url 'userslist:login' %}">Войти</a>
                <a class="nav-link active" style="color: aliceblue;" href="{% url 'userslist:register' %}">
                  Создать аккаунт</a>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-4 col-8">
      {% if messages %} {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
      {% endfor %} {% endif %} {% block content %} {% endblock %}
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
      integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
      integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
      crossorigin="anonymous"
    ></script>
    {% block body %}


    {% endblock %}
    <br>
  </body>
</html>

mysite/userslist/templates/userslist/file-upload.html
{% extends 'userslist/base.html' %}
 <title>
  {% block title %}
    File upload
  {% endblock %}
  </title>

<body>
  {% block body %}
  <h1>Upload file</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
    <input type="file" name="file">
    </p>
    <button type="submit">Upload</button>
  </form>
  {% endblock %}

</body>

mysite/userslist/templates/userslist/login.html
<!DOCTYPE html>
{% extends "userslist/base.html" %}
{% load static %}

<head>
  <meta charset="UTF-8">
  {% block title %}
    <title>Сайт простых рецептов.Авторизация</title>
  {% endblock %}

</head>
<body>
  {% block content %}

  <fieldset class="form-group">
    <legend class="border-bottom mb-4">Введите свои данные для авторизации</legend>
    <div class="container">
      <div class="login-form">
        <form method="post">
          {% csrf_token %}
          <fieldset class="form-group">
          {{ form.as_p }}
            <div class="form-group py-3">
              <button class="btn btn-outline-primary" type="submit">Войти   </button>
            </div>
            </fieldset>
        </form>
        <br>
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">Еще не зарегистрированы?</legend>
            <a class="btn btn-outline-primary" href="{% url 'userslist:register' %}">Регистрация</a>
          </fieldset>
        <br>
        <div class="form-group py-3">
          <a class="btn btn-outline-info" href="{% url 'recipesapp:index' %}">Вернуться на Главную</a>
        </div>
      </div>
    </div>
  </fieldset>
  {% endblock %}

</body>
</html>

mysite/userslist/templates/userslist/register.html
<!DOCTYPE html>
{% extends "userslist/base.html" %}
{% load static %}

<head>
  <meta charset="UTF-8">
  {% block title %}
    <title>Сайт простых рецептов.Регистрация</title>
  {% endblock %}
</head>

<body>
{% block content %}
  <fieldset class="form-group">
    <legend class="border-bottom mb-4">Заполните поля  для создания аккаунта</legend>
    <div class="container">
        <form method="post">
          {% csrf_token %}
          <fieldset class="form-group">
          {{ form.as_p }}
            <div class="form-group py-3">
              <button class="btn btn-outline-primary" type="submit">Зарегистрироваться</button>
            </div>
          </fieldset>
        </form>
    </div>
  </fieldset>
<br>
<fieldset class="form-group">
  <legend class="border-bottom mb-4">Уже зарегистированы?</legend>
  <a class="btn btn-outline-primary" href="{% url 'userslist:login' %}">Войти</a>
</fieldset>
<br>
<fieldset class="form-group">
<div class="form-group py-3">
  <a class="btn btn-outline-info" href="{% url 'recipesapp:index' %}">Вернуться на Главную</a>
</div>

</fieldset>
  {% endblock %}

</body>
</html>

mysite/userslist/templates/userslist/user-form.html
<!DOCTYPE html>

{% extends 'userslist/base.html' %}
{% load static %}

<html>
  {% block title %}
  <title> User</title>
  {% endblock %}

<body>
  {% block content %}
    <h1>User Form</h1>
    <div>
      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Submit
        </button>
      </form>
    </div>
  {% if request.POST %}
    <div>
      <h3>Form submitted successfully!</h3>
      <table>
        <tr>
          <td>First name:</td>
          <td>{{ request.POST.first_name }}</td>
        </tr>
        <tr>
          <td>Last name:</td>
          <td>{{ request.POST.last_name }}</td>
        </tr>
        <tr>
          <td>Age:</td>
          <td>{{ request.POST.age }}</td>
        </tr>
        <tr>
          <td>Email:</td>
          <td>{{ request.POST.email }}</td>
        </tr>
      </table>
    </div>
  {% endif %}
  {% endblock %}
</body>

</html>

mysite/userslist/templates/userslist/user_update_form.html
<!DOCTYPE html>
{% extends 'userslist/base.html' %}
{% load static %}

<html>
<head>
  <meta charset="utf-8" />
  {% block title %}
    <title>Сайт простых рецептов.Изменение профиля</title>
  {% endblock %}
</head>

<body>
  {% block content %}
  <h3 style="display: flex; justify-content: center;">Изменение данных пользователя {{ user.username }}</h3>
  <br>
  <div class="container">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">При необходимости внесите изменения в поля профиля</legend>
        {{ form.as_p }}
        <div class="form-group py-3">
          <label for="first_name">Изменить имя </label>
          <input type="text" class="form-control" id="first_name" name="first_name" value="{{ user.first_name }}">
        </div>
        <div class="form-group py-3">
          <label for="last_name">Изменить фамилию</label>
          <input type="text" class="form-control" id="last_name" name="last_name" value="{{ user.last_name }}">
        </div>
        <div class="form-group py-3">
          <label for="email">Изменить email</label>
          <input type="email" class="form-control" id="email" name="email" value="{{ user.email }}">
        </div>

        <div class="form-group py-3">
          <label for="date_of_birth">Изменить дату рождения</label>
          <input type="date" class="form-control" id="date_of_birth" name="date_of_birth" value="{{ user.profile.date_of_birth }}">
        </div>

        <div class="form-group py-3">
          <label for="photo">Изменить аватарку</label>
          <input type="file" class="form-control-file" id="photo" name="photo">
        </div>
      </fieldset>

      <div class="form-group py-3">
        <button class="btn btn-outline-info" >Сохранить изменения</button>
      </div>
      <div  class="form-group py-3">
        <a class="btn btn-outline-primary" href="{% url 'userslist:about-me' %}">Вернуться к профилю</a>
      </div>
    </form>
  </div>
  {% endblock %}
</body>
</html>