mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from recipesapp.views import RecipeIndexView

urlpatterns = [
    path("", RecipeIndexView.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('recipe/', include('recipesapp.urls')),
    path('user/', include('userslist.urls')),
    path('api/', include('myapiapp.urls')),
]

urlpatterns += i18n_patterns(
    path('user/', include('userslist.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

mysite/recipesapp/urls.py
from django.urls import path

from .views import RecipeIndexView,\
    RecipeListView, \
    RecipeDetailsView,\
    RecipeCreateView,\
    RecipeUpdateView,\
    RecipeDeleteView


app_name = 'recipesapp'

urlpatterns = [
    path('', RecipeIndexView.as_view(), name='index'),
    path('list/', RecipeListView.as_view(), name='list'),
    path('recipe/create/', RecipeCreateView.as_view(), name='recipe_create'),
    path('list/<int:pk>/', RecipeDetailsView.as_view(), name='recipe_details'),
    path('list/<int:pk>/update', RecipeUpdateView.as_view(), name='recipe_update'),
    path('list/<int:pk>/delete', RecipeDeleteView.as_view(), name='recipe_delete'),
]

mysite/userslist/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import get_cookie_view, \
    set_cookie_view, get_session_view, \
    set_session_view, logout_view,\
    AboutMeView, RegisterView,\
    HelloView, user_update

app_name = 'userslist'

urlpatterns = [
    path('login/',
         LoginView.as_view(template_name="userslist/login.html",
                            redirect_authenticated_user=True),
         name='login'),
    path('hello/', HelloView.as_view(), name='hello'),
    path('logout/', logout_view, name='logout'),
    path('about-me/', AboutMeView.as_view(), name='about-me'),
    path('register/', RegisterView.as_view(), name='register'),
    path('edit-user/', user_update, name='edit-user'),
    path('cookie/get', get_cookie_view, name='get-cookie'),
    path('cookie/set', set_cookie_view, name='set-cookie'),
    path('session/get', get_session_view, name='get-session'),
    path('session/set', set_session_view, name='set-session'),
]

mysite/recipesapp/models.py
from django.contrib.auth.models import User
from django.db import models

def recipe_photo_directory_path(instance:"Recipe", filename: str):
    return "recipies/recipe_{pk}/photo/{filename}".format(
        pk=instance.pk,
        filename=filename,)


class Recipe(models.Model):
    class Meta:
        verbose_name = "Recipe"
        # ordering = ['-created_at']  # Sort by most recently created first
        ordering = ['-title', 'created_at']

    title = models.CharField(max_length=150)
    description = models.TextField()
    steps_of_cooking = models.TextField()
    time_for_cooking = models.IntegerField(default=15)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    archived = models.BooleanField(default=False)
    photo = models.ImageField(null=True,  blank=True, upload_to=recipe_photo_directory_path)

    @property
    def description_short(self):
        if len(self.description) < 25:
            return self.description
        else:
            return self.description[:25] + "..."

    def __str__(self):
        return self.title

mysite/recipesapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Recipe


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = "title", "description", "steps_of_cooking", "time_for_cooking", "author", "archived"

mysite/recipesapp/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
import logging

from userslist.models import Profile
from .forms import RecipeForm
from .models import Recipe

log = logging.getLogger(__name__)


class RecipeIndexView(View):
    def get(self, request: HttpRequest):
        log.info("User accessed recipe index page")
        return render(request, "recipesapp/recipe-index.html")


class RecipeListView(ListView):
    template_name = 'recipesapp/recipes-list.html'
    # model = Recipe
    context_object_name = "recipes"
    queryset = Recipe.objects.filter(archived=False)


class RecipeDetailsView(DetailView):
    template_name = "recipesapp/recipe-details.html"
    model = Recipe
    context_object_name = "recipe"


class RecipeCreateView(CreateView):
    model = Recipe
    # form_class = RecipeForm
    fields = "title", "description", "steps_of_cooking", "time_for_cooking", "author", "photo"
    success_url = reverse_lazy('recipesapp:list')

    def form_valid(self, form):
        if form.instance.author == self.request.user:
            return super().form_valid(form)
        else:
            return HttpResponse("<h3>Вы можете создать рецепт только под своим именем!</h3>")


class RecipeUpdateView(UpdateView):
    model = Recipe
    fields = "title", "description", "steps_of_cooking", "time_for_cooking", "photo"
    template_name_suffix = "_update_form"
    def get_success_url(self):
        return reverse('recipesapp:recipe_details',
                       kwargs={"pk": self.object.pk}, )


class RecipeDeleteView(DeleteView):
    model = Recipe
    success_url = reverse_lazy('recipesapp:list')

# class RecipeDeleteView(PermissionRequiredMixin, DeleteView):
#     permission_required = 'recipesapp.delete_recipe'
#     model = Recipe
#     success_url = reverse_lazy('recipesapp:list')
#     def test_func(self):
#         recipe = self.get_object()
#         return self.request.user == recipe.author
#     def form_valid(self, form):
#         success_url = self.get_success_url()
#         self.object.archived = True
#         self.object.save()
#         return HttpResponseRedirect(success_url)

mysite/recipesapp/templates/recipesapp/base.html
<!DOCTYPE html>
{% load static %}

<html >
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% block title %}
      {% if title %}
         <title>{{title}}</title>
      {% else %}
        <title>Сайт простых рецептов</title>
      {% endif %}
    {% endblock %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
      crossorigin="anonymous"
    />
    <link rel="icon" href="../../../media/free-icon-chef-hat-8560938.png" type="image/x-icon">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="nav-link active" style="color: aliceblue;" href="{% url 'recipesapp:index' %}">Главная</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="nav-link active" style="color: aliceblue;" href="{% url 'recipesapp:list' %}">Рецепты</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="d-flex justify-content-end" id="navbarNav">
          <ul class="navbar-nav">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" style="color: aliceblue;" href="{% url 'recipesapp:recipe_create' %}">
                  Добавить рецепт</a>
              </li>
                <a href="{% url 'userslist:about-me' %}" class="nav-link active" style="color: aliceblue;">Мой профиль</a>
                <a  class="nav-link active" style="color: aliceblue;" href="{% url 'userslist:logout' %}">Выйти</a>

              {% else %}
                <a class="nav-link active" style="color: aliceblue;" href="{% url 'userslist:login' %}">Войти</a>
                <a class="nav-link active" style="color: aliceblue;" href="{% url 'userslist:register' %}">
                  Создать аккаунт</a>
              {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-4 col-8">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
      {% block content %}
      {% endblock %}
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
      integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
      integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
      crossorigin="anonymous"
    ></script>
    {% block body %}{% endblock %}
    <br>
  </body>
</html>

mysite/recipesapp/templates/recipesapp/create-recipe.html
<!DOCTYPE html>
{% extends "recipesapp/base.html" %}
{% load static %}

<html>
  <head>
    <meta charset="utf-8" />
    {% block title %}
      <title>Сайт простых рецептов.Создание рецепта</title>
    {% endblock %}
  </head>

  <body>

    {% block body %}
      <h3 style="display: flex; justify-content: center; color:red; ">Создание нового рецепта:</h3>
      <h4 style="text-align:left; color: blue;" >Введите новый рецепт в форму</h4>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Создать рецепт</button>
      </form>
      <br>
      <div>
        <a style="text-decoration: none; color: red;" href="{% url 'recipesapp:list' %}"><b>
          Вернуться к списку рецептов</b></a>
      </div>

  {% endblock %}
  </body>
</html>

mysite/recipesapp/templates/recipesapp/recipe-details.html
<!DOCTYPE html>
{% extends "recipesapp/base.html" %}
{% load static %}

<html>
  <head>
    <meta charset="utf-8" />
    {% block title %}
      <title>Сайт простых рецептов.Рецепт №{{ recipe.pk }}</title>
    {% endblock %}
  </head>
  <body>
    {% block content %}
    <div class="card mb-3">
      <div class="card-body">
        <h4 class="card-title"> <em>{{ recipe.title }}</em></h4>
        <p class="card-text"><b>Описание:</b></p>
        <p> {{ recipe.description }}</p>
        <br>
        <p class="card-text"><b>Шаги приготовления:</b></p>
        <p>{{ recipe.steps_of_cooking }}</p>
        <p class="card-text"><b>Время приготовления</b>: {{ recipe.time_for_cooking }} мин.</p>
        <h6 class="card-subtitle mb-2 text-muted">Автор: {{ recipe.author }}</h6>
      {% if recipe.photo %}
        <div>
            <img class="card-img-top" style="width:50%" src="{{ recipe.photo.url }}" alt="">
        </div>
      {% else %}
        <p class="card-text" style="color:red"><em><b>К сожалению, фото рецепта отсутствует.</b></em></p>
      {% endif %}
      <div>
        <p class="card-subtitle mb-2 text-muted" style="color:grey">Дата создания: {{ recipe.created_at|date:"F d, Y" }}</p>
      </div>
     </div>
    </div>

    {% if object.author == user or user.is_staff %}
      <div class="form-group py-3">
        <a class="btn btn-outline-info" href="{% url 'recipesapp:recipe_update' pk=recipe.pk %}">Изменить рецепт</a>
      </div>
      <div class="form-group py-3">
        <a class="btn btn-outline-danger" href="{% url 'recipesapp:recipe_delete' pk=recipe.pk %}">Удалить рецепт</a>
      </div>
      <div class="form-group py-3">
        <a class="btn btn-outline-primary" href="{% url 'recipesapp:list' %}">Вернуться к списку рецептов</a>
      </div>
    {% else %}
    <div class="form-group py-3">
      <a class="btn btn-outline-primary" href="{% url 'recipesapp:list' %}">Вернуться к списку рецептов</a>
    </div>
    {% endif %}
    {% endblock %}
  </body>
</html>

mysite/recipesapp/templates/recipesapp/recipe-index.html
<!DOCTYPE html>
{% extends "recipesapp/base.html" %}
{% load static}

<html>
<head>
  {% block title %}
  <title>Сайт простых рецептов.Главная</title>
  {% endblock %}

</head>
<body>
{% block body %}
  <h3 style="text-align: center; ">Добро пожаловать на наш сайт полезных и вкусных рецептов!</h3>
  <div style="width: 100vw; height: 70vh; display: flex; align-items: center; justify-content: center;">
    <img style="max-width: 90%;  max-height: 70%; display: block;" src="https://prorisuem.ru/foto/9315/risunok_zdorovaia_eda_19.webp">
  </div>
  <h4 style="text-align: center; color:#DD3333;">Готовьте быстро, просто и вкусно с нашим сайтом! </h4>
  <h4 style="text-align: center; color:#DD3333;">Наши рецепты помогут Вам cэкономить время и угодить всем вкусам!</h4>

  {% endblock %}

</body>
</html>

mysite/recipesapp/templates/recipesapp/recipe_confirm_delete.html
<!DOCTYPE html>
{% extends "recipesapp/base.html" %}
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  {% block title %}
    <title>Сайт простых рецептов.Удаление рецепта </title>
  {% endblock %}
</head>
<body>
  {% block content %}
    <div class="container">
      <form method="post">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="mb-4">Вы уверены, что хотите удалить рецепт "{{recipe.title}}" ?</legend>
          {{ form.as_p }}
        </fieldset>
        <div class="form-group py-3">
          <button class="btn btn-outline-danger" type="submit">Удалить рецепт</button>
          <a class="btn btn-outline-info" style="height: 43px; width: 200px; margin-left: 20px;"
             href="{% url 'recipesapp:recipe_details' pk=recipe.pk %}">
            Вернуться к рецепту </a>
        </div>
      </form>
    </div>
  {% endblock %}
</body>
</html>

mysite/recipesapp/templates/recipesapp/recipe_form.html
<!DOCTYPE html>
{% extends "recipesapp/base.html" %}
{% load static %}

<html>
<head>
  <meta charset="utf-8" />
  {% block title %}
    <title>Сайт простых рецептов.Новый рецепт</title>
  {% endblock %}
</head>
<body>
  {% block content %}
  <div class="container">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
      <legend class="border-bottom mb-4">Заполните все поля нового рецепта</legend>
      {{ form.as_p }}
      </fieldset>
        <div class="form-group py-3">
        <button class="btn btn-outline-primary"  type="submit" >Создать рецепт</button>
        <a class="btn btn-outline-primary" style="height: 43px; width: 250px; margin-left: 20px;"
           href="{% url 'recipesapp:list' %}">Вернуться к списку рецептов</a>
        </div>
    </form>
  </div>
  {% endblock %}
</body>
</html>

mysite/recipesapp/templates/recipesapp/recipe_update_form.html
<!DOCTYPE html>
{% extends "recipesapp/base.html" %}
{% load static %}

<html>
<head>
  <meta charset="utf-8" />
  {% block title %}
    <title>Сайт простых рецептов.Изменение рецепта</title>
  {% endblock %}
</head>

<body>
  {% block content %}
  <h3 style="display: flex; justify-content: center;">Изменение рецепта "{{recipe.title}}"</h3>
  <br>
  <div class="container">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Измените все необходимые поля данного рецепта</legend>
        {{ form.as_p }}
      </fieldset>
      <div class="form-group py-3">
        <button class="btn btn-outline-info" type="submit">Сохранить изменения</button>
      </div>
      <div  class="form-group py-3">
        <a class="btn btn-outline-primary" style="height: 55px; width: 250px;"
           href="{% url 'recipesapp:recipe_details' pk=recipe.pk %}">Вернуться к рецепту без сохранения изменений</a>
      </div>
    </form>
  </div>
  {% endblock %}
</body>
</html>

mysite/recipesapp/templates/recipesapp/recipes-list.html
<!DOCTYPE html>
{% extends "recipesapp/base.html" %}
{% load static}

<html>
<head>
{% block title %}
  <title>Сайт простых рецептов. Рецепты</title>
{% endblock %}
</head>
<body>
{% block content %}
  <h3 style="display: flex; justify-content: center; color: #DD3333">Добро пожаловать на наш замечательный сайт,
    где каждое блюдо — настоящее произведение искусства. </h3>
    <p style="display: flex; justify-content: center;">Здесь вы найдете простые рецепты, наполненные свежестью
      и ароматом. И в то же время наши рецепты призваны удовлетворить ваши самые изысканные  кулинарные желания!</p>
<br>
  {% if recipes  %}
    {% for recipe in recipes %}
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title">
          <a href= "{% url 'recipesapp:recipe_details' pk=recipe.pk %}" class="card-link" style="text-decoration: none;
            color:black">{{ recipe.title }}
          </a></h5>
          <p>
            {% if recipe.photo %}
              <a href= "{% url 'recipesapp:recipe_details' pk=recipe.pk %}">
                <img class="card-img-top" style="width:50%" src="{{ recipe.photo.url }}" alt="" >
              </a>
            {% endif %}
          </p>
          <p class="card-text">{{ recipe.description }}</p>
          <p class="card-text"><b>Время приготовления</b>: {{ recipe.time_for_cooking }} мин.</p>
          <a href="{% url 'recipesapp:recipe_details' pk=recipe.pk %}" class="btn btn-primary">Подробнее о рецепте</a>
      </div>
    </div>
    {% endfor %}
      <br>
  {% else %}
    <h3>No recipes found.</h3>
  {% endif %}
    <br>
{% endblock %}
</body>